version: '3.8'

services:
  web:
    image: django
    build:
      context: ./back_end
      dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back_end/:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - risk_forum:/var/lib/postgresql/data
      - ./database/:/code
    environment:
      POSTGRES_DB: 'risk_forum'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
    ports:
      - 5432:5432

  frontend:
    image: react
    build: 
      context: ./front_end
      dockerfile: Dockerfile
    command: npm run serve -- --host 0.0.0.0
    volumes:
      - ./front_end/app/:/app
      - /app/node_modules
    ports:
      - 4173:4173
    depends_on:
      - web

volumes:
  risk_forum:
