# Generated by Django 5.0 on 2024-01-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240127_1453'),
    ]

    operations = [
    ]
