# Generated by Django 5.0 on 2024-01-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20240128_1528'),
    ]

    operations = [
    ]
