# Generated by Django 5.0 on 2024-01-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20240128_1555'),
    ]

    operations = [
    ]
