# Generated by Django 5.0 on 2024-01-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20240128_1611'),
    ]

    operations = [
    ]
