# Generated by Django 5.0 on 2024-01-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20240128_1633'),
    ]

    operations = [
    ]
