
# Generated by Django 5.0 on 2024-01-21 21:45
# Generated by Django 5.0 on 2024-01-23 18:37


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('business', models.CharField(max_length=100)),
                ('professional', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=100)),
                ('ceo_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
